export const SQL_KEYWORDS = [
	'ABORT', 'ACTION', 'ADD', 'AFTER', 'ALL', 'ALTER', 'AND', 'AS', 'ASC',
	'AUTOINCREMENT', 'BEFORE', 'BEGIN', 'BETWEEN', 'BLOB', 'BOOLEAN', 'BY',
	'CASCADE', 'CASE', 'CAST', 'CHECK', 'COLLATE', 'COLUMN', 'COMMIT',
	'CONFLICT', 'CONSTRAINT', 'COUNT', 'CREATE', 'CROSS', 'CURRENT_DATE',
	'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DATABASE', 'DEFAULT', 'DELETE',
	'DESC', 'DISTINCT', 'DROP', 'EACH', 'ELSE', 'END', 'ESCAPE', 'EXCEPT',
	'EXISTS', 'EXPLAIN', 'FOREIGN', 'FROM', 'FULL', 'GLOB', 'GROUP',
	'HAVING', 'IF', 'IGNORE', 'IN', 'INDEX', 'INNER', 'INSERT', 'INTEGER',
	'INTERSECT', 'INTO', 'IS', 'JOIN', 'KEY', 'LEFT', 'LIKE', 'LIMIT',
	'NOT', 'NULL', 'OFFSET', 'ON', 'OR', 'ORDER', 'OUTER', 'PRAGMA',
	'PRIMARY', 'REAL', 'RECURSIVE', 'REFERENCES', 'REPLACE', 'RESTRICT',
	'RIGHT', 'ROLLBACK', 'ROW', 'SELECT', 'SET', 'TABLE', 'TEXT', 'THEN',
	'TRANSACTION', 'TRIGGER', 'UNION', 'UNIQUE', 'UPDATE', 'USING',
	'VACUUM', 'VALUES', 'VIEW', 'VIRTUAL', 'WHEN', 'WHERE', 'WITH',
];

export const BACKSLASH_COMMANDS = [
	'\\dt', '\\d', '\\di', '\\T', '\\timing', '\\?', '\\q', '\\help',
];
